service: chat-backend-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

  environment:
    WSS_APIGATEWAY_ENDPOINT:
      Fn::Join:
        - ""
        - - Ref: WebsocketsApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/${sls:stage}"


  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:deleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["UsersTable", "Arn"] }
        - Effect: Allow
          Action:
            - "dynamodb: Query"
          Resource:
            Fn::Join:
              - "/"
              - - { "Fn::GetAtt": ["UsersTable", "Arn"] }
                - "index"
                - "*"
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:deleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["MessagesTable", "Arn"] }
        - Effect: Allow
          Action:
            - "dynamodb: Query"
          Resource:
            Fn::Join:
              - "/"
              - - { "Fn::GetAtt": ["MessagesTable", "Arn"] }
                - "index"
                - "*"

functions:
  websocketHandler:
    handler: app/handlers.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: getUsers
      - websocket:
          route: sendMessage
      - websocket:
          route: getMessages

  hello:
    handler: app/handlers.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-auto-swagger
  - serverless-plugin-typescript
  - serverless-offline
  
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserNameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            Projection:
              ProjectionType: "ALL"
              
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Messages
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
          - AttributeName: usernameToUsername
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UsernameToUsernameIndex
            KeySchema:
              - AttributeName: usernameToUsername
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            Projection:
              ProjectionType: "ALL"
              